### ISSUE TITLE
maven无法获取到blade-velocity-1.2

### ISSUE THREAD

**Issue by shinestmt** [bladejava/blade-sample#1]
从github上获取到源码后，执行mvn，依赖的blade-velocity-1.2无法获取到，而其他依赖都是没问题的

*在http://search.maven.org/ 中搜索blade-velocity, 只有1.1.1的版本, 没有1.2, 已经手工解决.*
*还是希望您能抽空解决一下这个问题, 避免对其他使用者造成困扰*

**Comment by biezhi** [comment]
已经解决了，正在发布中，昨天因为网速原因我没有上传，今天统一全部都在1.2版本
